"""add settings_requests and settings_snapshots tables

Revision ID: 0f1097258abc
Revises: c3a8f2b1d4e5
Create Date: 2026-02-01 17:35:48.123134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1097258abc'
down_revision: Union[str, None] = 'c3a8f2b1d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_requests',
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('settings_snapshots',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('ciphertext', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('aad_node_id', sa.String(), nullable=False),
    sa.Column('aad_schema_version', sa.Integer(), nullable=False),
    sa.Column('aad_commands_schema_version', sa.Integer(), nullable=False),
    sa.Column('aad_revision', sa.Integer(), nullable=False),
    sa.Column('aad_request_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['settings_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_snapshots')
    op.drop_table('settings_requests')
    # ### end Alembic commands ###
