import logging
import os
from datetime import datetime
from typing import List, Optional

import httpx
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, ConfigDict
from sqlalchemy.orm import Session

from .core.conversation_cache import conversation_cache
from .context_providers.node_context_provider import NodeContextProvider
from .deps import (
    AuthenticatedUser,
    get_db,
    verify_admin_key,
    verify_api_key,
    verify_household_role,
    verify_user_jwt,
)
from .api.node_updates import dispatch_pending_task, reconcile_open_task
from .models import AuthSession, ConfigPush, Node, SettingsRequest, SettingsSnapshot


router = APIRouter()
logger = logging.getLogger("uvicorn")


# ============================================================
# Configuration
# ============================================================

JARVIS_APP_ID = os.getenv("JARVIS_APP_ID", "command-center")
JARVIS_APP_KEY = os.getenv("JARVIS_APP_KEY")


def _get_auth_base_url() -> str:
    """Get auth service URL from service discovery or fallback to env var."""
    try:
        from app.core import service_config
        if service_config.is_initialized():
            return service_config.get_auth_url()
    except (ImportError, AttributeError):
        pass
    return os.getenv("JARVIS_AUTH_BASE_URL", "http://localhost:7701")


# ============================================================
# Request/Response Models
# ============================================================


class NodeResponse(BaseModel):
    """Response model for node operations (local data only)."""
    node_id: str
    room: str
    user: str
    voice_mode: str | None = "brief"
    adapter_hash: Optional[str] = None
    household_id: str | None = None
    online: bool = False
    last_seen: datetime | None = None
    # Populated from heartbeat; all optional so pre-upgrade nodes stay valid.
    last_seen_version: str | None = None
    install_mode: str | None = None
    git_sha: str | None = None
    is_busy: bool = False

    model_config = ConfigDict(from_attributes=True)


class HeartbeatPayload(BaseModel):
    """POST body for /admin/nodes/heartbeat.

    All fields optional so older node versions still heartbeat successfully.
    """
    thread_status: dict | None = None
    version_info: dict | None = None
    is_busy: bool | None = None


class NodeCreateResponse(BaseModel):
    """Response model for node creation (includes node_key)."""
    node_id: str
    room: str
    user: str
    voice_mode: str | None = "brief"
    node_key: str  # Only returned on creation


class NodeCreate(BaseModel):
    """Request model for creating a node.

    Node is registered with jarvis-auth first, then local record is created.
    The api_key is generated by jarvis-auth and stored locally.
    """
    node_id: str
    household_id: str
    name: Optional[str] = None  # Defaults to node_id
    room: str
    user: str = "default"
    voice_mode: str = "brief"


class NodeUpdate(BaseModel):
    """Request model for updating a node (local fields only)."""
    room: Optional[str] = None
    user: Optional[str] = None
    voice_mode: Optional[str] = None
    adapter_hash: Optional[str] = None


# ============================================================
# jarvis-auth Integration
# ============================================================


def _register_node_with_auth(
    node_id: str,
    household_id: str,
    name: str,
) -> str:
    """Register a node with jarvis-auth and return the node_key.

    Uses app-to-app auth. The calling service (command-center) is
    automatically granted access to the node.

    Returns:
        node_key: The generated API key for this node

    Raises:
        HTTPException: If registration fails
    """
    if not JARVIS_APP_KEY:
        raise HTTPException(
            status_code=500,
            detail="JARVIS_APP_KEY not configured for auth integration"
        )

    auth_url = _get_auth_base_url().rstrip("/") + "/internal/nodes/register"

    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.post(
                auth_url,
                headers={
                    "X-Jarvis-App-Id": JARVIS_APP_ID,
                    "X-Jarvis-App-Key": JARVIS_APP_KEY,
                },
                json={
                    "node_id": node_id,
                    "household_id": household_id,
                    "name": name,
                    "services": [],  # command-center is auto-added by jarvis-auth
                },
            )
    except httpx.RequestError as exc:
        logger.error(f"Failed to reach jarvis-auth: {exc}")
        raise HTTPException(
            status_code=502,
            detail=f"Auth service unavailable: {exc}"
        ) from exc

    if resp.status_code == 201:
        data = resp.json()
        logger.info(f"Node registered with jarvis-auth: {node_id}")
        return data["node_key"]
    elif resp.status_code == 400:
        detail = resp.json().get("detail", "Node already exists")
        raise HTTPException(status_code=400, detail=detail)
    elif resp.status_code == 404:
        detail = resp.json().get("detail", "Household not found")
        raise HTTPException(status_code=404, detail=detail)
    else:
        logger.error(f"jarvis-auth registration failed: {resp.status_code} - {resp.text}")
        raise HTTPException(
            status_code=resp.status_code,
            detail=f"Auth service error: {resp.text}"
        )


def _deactivate_node_with_auth(node_id: str) -> bool:
    """Deactivate a node in jarvis-auth.

    Returns True if successful or node not found, False on error.
    """
    if not JARVIS_APP_KEY:
        logger.warning("JARVIS_APP_KEY not configured, skipping auth deactivation")
        return True

    auth_url = _get_auth_base_url().rstrip("/") + f"/internal/nodes/{node_id}"

    try:
        with httpx.Client(timeout=10.0) as client:
            resp = client.delete(
                auth_url,
                headers={
                    "X-Jarvis-App-Id": JARVIS_APP_ID,
                    "X-Jarvis-App-Key": JARVIS_APP_KEY,
                },
            )
    except httpx.RequestError as exc:
        logger.error(f"Failed to reach jarvis-auth for deactivation: {exc}")
        return False

    if resp.status_code == 200:
        logger.info(f"Node deactivated in jarvis-auth: {node_id}")
        return True
    elif resp.status_code == 404:
        logger.warning(f"Node {node_id} not found in jarvis-auth (may already be deleted)")
        return True
    else:
        logger.error(f"Failed to deactivate node in jarvis-auth: {resp.status_code}")
        return False


# ============================================================
# Node CRUD Endpoints
# ============================================================


@router.get("/nodes", response_model=List[NodeResponse])
def list_nodes(household_id: str | None = None, db: Session = Depends(get_db)):
    """List nodes registered with this command center.

    Args:
        household_id: Optional filter by household UUID.
    """
    query = db.query(Node)
    if household_id:
        query = query.filter(Node.household_id == household_id)
    nodes = query.all()

    results: list[NodeResponse] = []
    for node in nodes:
        resp = NodeResponse.model_validate(node)
        resp.online = node.is_online()
        results.append(resp)
    return results


@router.get("/nodes/{node_id}", response_model=NodeResponse)
def get_node(node_id: str, db: Session = Depends(get_db)):
    """Get a single node by ID."""
    node = db.query(Node).filter(Node.node_id == node_id).first()
    if not node:
        raise HTTPException(status_code=404, detail="Node not found")
    resp = NodeResponse.model_validate(node)
    resp.online = node.is_online()
    return resp


@router.post("/nodes/heartbeat")
def node_heartbeat(
    payload: HeartbeatPayload | None = None,
    node_context: NodeContextProvider = Depends(verify_api_key),
    db: Session = Depends(get_db),
):
    """Receive heartbeat from a node and update status fields.

    Also the dispatch channel for pending node tasks — if there's one queued
    and the node isn't busy, it's returned in `pending_update`. Tasks are
    marked "dispatched" so we don't re-send on every heartbeat; the node's
    post-upgrade heartbeat confirms success by reporting the new version.
    """
    node = db.query(Node).filter(
        Node.node_id == node_context.node.node_id,
    ).first()
    if not node:
        return {"status": "ok"}

    node.last_seen = datetime.utcnow()
    reported_version: str | None = None
    if payload is not None:
        if payload.version_info:
            reported_version = payload.version_info.get("version")
            node.last_seen_version = reported_version
            node.install_mode = payload.version_info.get("install_mode")
            node.git_sha = payload.version_info.get("git_sha")
        if payload.is_busy is not None:
            node.is_busy = payload.is_busy
    db.commit()

    # If the node just reported its post-upgrade version, finalize any
    # open update task that was waiting on that version.
    reconcile_open_task(db, node, reported_version)

    # If there's something queued for this node (and it's not busy), hand
    # it over now — the node's update_service picks it up on the response.
    response: dict = {"status": "ok"}
    pending = dispatch_pending_task(db, node)
    if pending is not None:
        response["pending_update"] = pending
    return response


@router.post("/nodes", response_model=NodeCreateResponse, dependencies=[Depends(verify_admin_key)])
def create_node(node: NodeCreate, db: Session = Depends(get_db)):
    """Create a new node.

    This registers the node with jarvis-auth (for authentication) and
    creates a local record (for room/user/voice_mode context).

    The node_key is generated by jarvis-auth and returned only once.
    Store it securely in the node's config.json.
    """
    # Check if node already exists locally
    existing = db.query(Node).filter(Node.node_id == node.node_id).first()
    if existing:
        raise HTTPException(status_code=400, detail="Node already exists locally")

    # Register with jarvis-auth first
    name = node.name or node.node_id
    node_key = _register_node_with_auth(node.node_id, node.household_id, name)

    # Create local record
    db_node = Node(
        node_id=node.node_id,
        api_key=node_key,  # Store for legacy compatibility
        room=node.room,
        user=node.user,
        voice_mode=node.voice_mode,
    )
    db.add(db_node)
    db.commit()
    db.refresh(db_node)

    logger.info(f"Node created: {db_node.node_id} in room {db_node.room}")

    return NodeCreateResponse(
        node_id=db_node.node_id,
        room=db_node.room,
        user=db_node.user,
        voice_mode=db_node.voice_mode,
        node_key=node_key,
    )


@router.delete("/nodes/{node_id}")
def delete_node(
    node_id: str,
    db: Session = Depends(get_db),
    user: AuthenticatedUser = Depends(verify_user_jwt),
):
    """Delete a node. Requires power_user or admin role in the node's household."""
    node = db.query(Node).filter(Node.node_id == node_id).first()

    if not node:
        raise HTTPException(status_code=404, detail="Node not found")

    if node.household_id:
        # Verify the user has power_user (or admin) role in this household
        verify_household_role(user.user_id, node.household_id, required_role="power_user")
    elif not user.is_superuser:
        raise HTTPException(
            status_code=403,
            detail="Only superusers can delete nodes without a household",
        )

    # Attempt to deactivate in jarvis-auth
    _deactivate_node_with_auth(node_id)

    # Delete referencing records before removing the node
    for model in (AuthSession, ConfigPush, SettingsRequest, SettingsSnapshot):
        db.query(model).filter(model.node_id == node_id).delete()

    # Delete local record
    db.delete(node)
    db.commit()
    logger.info(f"Node deleted: {node.node_id} by user {user.user_id}")
    return {"message": "Deleted"}


@router.patch("/nodes/{node_id}", response_model=NodeResponse, dependencies=[Depends(verify_admin_key)])
def update_node(node_id: str, payload: NodeUpdate, db: Session = Depends(get_db)):
    """Update a node's local settings (room, user, voice_mode)."""
    node = db.query(Node).filter(Node.node_id == node_id).first()
    if not node:
        raise HTTPException(status_code=404, detail="Node not found")

    data = payload.model_dump(exclude_unset=True)
    for key, value in data.items():
        setattr(node, key, value)

    db.commit()
    db.refresh(node)
    logger.info(f"Node updated: {node.node_id}")
    return node


# ============================================================
# Cache Management Endpoints
# ============================================================


@router.get("/cache/stats")
def get_cache_stats():
    """Get conversation cache statistics."""
    return conversation_cache.stats()


@router.post("/cache/clear")
def clear_cache():
    """Clear all expired conversation cache entries."""
    cleared_count = conversation_cache.clear_expired()
    return {"message": f"Cleared {cleared_count} expired entries", "cleared_count": cleared_count}


@router.delete("/cache/{conversation_id}")
def remove_conversation(conversation_id: str):
    """Remove a specific conversation from the cache."""
    conversation_cache.remove(conversation_id)
    return {"message": f"Removed conversation {conversation_id[:8]}... from cache"}
