"""
JarvisLlama3B Model Implementation.

This is a first-party fine-tuned Llama 3.2 3B model that demonstrates
the power of good fine-tuning. It can perform single-shot inference
because it was trained on the same complex prompts that BaseModel generates.

The "magic" is that the model learned to do all the complex reasoning
internally during training, so the inference interface can be much simpler.
"""

import json
import logging
import time
from typing import Dict, Any, List, Optional

from app.core.models.base_model import BaseModel
from app.core.llm_manager import LLMManager
from app.core.conversation_cache import conversation_cache
from app.core.general_context import get_general_context
from app.request_models.voice_command_request import CommandDefinition

logger = logging.getLogger("uvicorn")

class JarvisLlama3B(BaseModel):
    """
    JarvisLlama3B: First-party fine-tuned Llama 3.2 3B model.
    
    This model was fine-tuned on training data generated by the BaseModel's
    complex prompt system. As a result, it can perform single-shot inference
    with much simpler prompts while maintaining the same quality.
    
    Key features:
    - Single LLM call for complete inference
    - Learned complex reasoning during training
    - Optimized for speed and simplicity
    - Maintains full compatibility with Jarvis response format
    """
    
    @property
    def name(self) -> str:
        return "JarvisLlama3B"
    
    async def perform_warmup(
        self,
        node_context: Dict[str, Any],
        available_commands: List[CommandDefinition],
        conversation_id: str,
        timezone: Optional[str] = None
    ) -> None:
        """
        Simplified warmup for fine-tuned model.
        
        Since the model was trained on complex prompts, we can use
        a much simpler warmup while maintaining the same functionality.
        """
        start_time = time.time()
        
        logger.info(f"🚀 JarvisLlama3B warmup for {conversation_id[:8]}...")
        
        try:
            # Build simplified but complete context
            system_prompt = self._build_single_shot_system_prompt(
                node_context=node_context,
                available_commands=available_commands,
                conversation_id=conversation_id,
                timezone=timezone
            )
            
            # Simple warmup messages
            warmup_messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": "This is a warm-up message to establish context."},
                {"role": "assistant", "content": "I understand. I'm ready to help with command inference and parameter extraction."}
            ]
            
            # Cache conversation
            conversation_cache.set(
                conversation_id=conversation_id,
                messages=warmup_messages,
                available_commands=[cmd.model_dump() for cmd in available_commands],
                timezone=timezone
            )
            
            # Warmup the LLM
            await self.llm_manager.warmup_conversation(
                conversation_id=conversation_id,
                warmup_messages=warmup_messages
            )
            
            duration = time.time() - start_time
            logger.info(f"✅ JarvisLlama3B warmup completed in {duration:.2f}s")
            
        except Exception as e:
            logger.error(f"❌ JarvisLlama3B warmup failed: {e}")
            raise
    
    async def perform_inference(
        self,
        voice_command: str,
        conversation_id: str,
        node_context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Single-shot inference - the magic of fine-tuning!
        
        This model can do in one call what BaseModel does in multiple steps
        because it learned the complex reasoning during training.
        """
        start_time = time.time()
        
        logger.info(f"🎯 JarvisLlama3B single-shot inference: '{voice_command}'")
        
        try:
            # Get cached conversation
            cached_messages = conversation_cache.get_messages(conversation_id)
            if not cached_messages:
                logger.error("❌ No cached conversation found")
                return {
                    "s": False,
                    "n": None,
                    "p": {},
                    "e": {"type": "cache_error", "message": "No conversation context found"}
                }
            
            # Single LLM call with the voice command
            messages = cached_messages.copy()
            messages.append({"role": "user", "content": voice_command})
            
            response = await self.llm_manager.llm_client.chat_completion(
                messages=messages,
                conversation_id=conversation_id
            )
            
            # Extract and parse response
            content = self.llm_manager._extract_content_from_response(response)
            if not content:
                raise ValueError("Empty response from model")
            
            # Parse JSON response
            try:
                result = json.loads(content.strip())
                
                # Validate response format
                if not isinstance(result, dict) or "s" not in result:
                    raise ValueError("Invalid response format")
                
                # Ensure all required fields are present
                result.setdefault("s", False)
                result.setdefault("n", None)
                result.setdefault("p", {})
                result.setdefault("e", None)
                
                duration = time.time() - start_time
                logger.info(f"✅ JarvisLlama3B inference completed in {duration:.2f}s")
                logger.info(f"   Single-shot result: {result}")
                
                return result
                
            except json.JSONDecodeError as e:
                logger.error(f"❌ Failed to parse JSON response: {content}")
                return {
                    "s": False,
                    "n": None,
                    "p": {},
                    "e": {"type": "parse_error", "message": f"Invalid JSON: {str(e)}"}
                }
                
        except Exception as e:
            logger.error(f"❌ JarvisLlama3B inference failed: {e}")
            return {
                "s": False,
                "n": None,
                "p": {},
                "e": {"type": "inference_error", "message": str(e)}
            }
    
    def _build_single_shot_system_prompt(
        self,
        node_context: Dict[str, Any],
        available_commands: List[CommandDefinition],
        conversation_id: str,
        timezone: Optional[str] = None
    ) -> str:
        """
        Build simplified system prompt for fine-tuned model.
        Uses exact same format as GeneralPromptProvider.build_complete_static_prompt.
        """
        # Get basic date context
        general_context_str = get_general_context(timezone)
        
        # Build node context string
        node_context_str = '\n'.join(f"{k}: {v}" for k, v in node_context.items()) if node_context else "No specific context"
        
        # Add conversation ID at the beginning if provided (matching old system)
        conversation_prefix = f"Conversation ID: {conversation_id}\n\n" if conversation_id else ""
        
        # Build available commands string using the same simple format as old system
        available_commands_str = "No commands available"
        if available_commands:
            available_commands_str = '\n'.join(
                f"- {cmd.command_name} - {cmd.description}"
                for cmd in available_commands
            )
        
        # Use exact same format as GeneralPromptProvider.build_complete_static_prompt
        system_prompt = f"""{conversation_prefix}You are an inference engine for a voice assistant. Ultimately, your job is to match a command name and parameters from a voice command to a set of available commands.

{general_context_str}

Node Context: {node_context_str}

You are a voice assistant command classifier. Identify which command the user wants.

COMMANDS & EXAMPLES:

{available_commands_str}

Always respond with JSON: {{"s":true,"n":"command_name","e":null}}"""
        
        return system_prompt
    
    def get_capabilities(self) -> Dict[str, Any]:
        """Return JarvisLlama3B capabilities."""
        return {
            "supports_single_shot": True,
            "supports_streaming": False,
            "max_context_length": 8192,
            "supported_languages": ["en"],
            "custom_features": {
                "fine_tuned_for_jarvis": True,
                "single_shot_inference": True,
                "optimized_prompts": True,
                "fast_inference": True
            }
        }
    
    async def health_check(self) -> Dict[str, Any]:
        """Health check for JarvisLlama3B."""
        return {
            "status": "healthy",
            "model_name": self.name,
            "details": {
                "model_type": "fine_tuned_llama_3.2_3b",
                "inference_mode": "single_shot",
                "training_data": "jarvis_command_inference_v1"
            }
        }
